name: Ruff Lint and Format

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Run Ruff linter
      - name: Run Ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          src: "./src"
      # Run import sorting check
      - name: Run import sorting check
        uses: astral-sh/ruff-action@v3
        with:
          src: "./src"
          args: check --select I
      # Run Ruff formatter check
      - name: Run Ruff formatter check
        uses: astral-sh/ruff-action@v3
        with:
          src: "./src"
          args: format --check
